require('dotenv').config();
const mongoose = require('mongoose');
const Place = require('./models/Place');

const places = [
  // MOUNTAINS
  { name: 'Spiti Valley', state: 'Himachal Pradesh', category: 'mountain', description: 'A cold desert mountain valley nestled high in the Himalayas, home to ancient monasteries and dramatic landscapes. Spiti sits at an average altitude of 4,270m, making it one of the highest inhabited regions in the world.', shortDescription: 'High-altitude cold desert with ancient monasteries', lat: 32.2461, lng: 78.0338, imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800', photos: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=400', 'https://images.unsplash.com/photo-1587135991058-8816b028691f?w=400'], popularActivities: ['Trekking', 'Monastery visits', 'Stargazing', 'Fossil hunting'], bestSeason: 'June – September', trending: true, wishlistCount: 2340 },
  { name: 'Rohtang Pass', state: 'Himachal Pradesh', category: 'mountain', description: 'A high mountain pass in the Himalayas, offering spectacular views of glaciers, peaks and valleys. It lies on the watershed of the Beas and Chenab rivers at 3,978m.', shortDescription: 'High mountain pass with glacier views', lat: 32.3722, lng: 77.2457, imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800', photos: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400'], popularActivities: ['Snowboarding', 'Snow activities', 'Photography', 'Paragliding'], bestSeason: 'May – October', trending: false, wishlistCount: 1850 },
  { name: 'Kedarnath', state: 'Uttarakhand', category: 'mountain', description: 'A sacred Hindu town at 3,583m in the Himalayas, home to one of the twelve Jyotirlingas of Lord Shiva. The trek through breathtaking Himalayan scenery adds to its mystical appeal.', shortDescription: 'Sacred Shiva shrine in the high Himalayas', lat: 30.7352, lng: 79.0669, imageUrl: 'https://images.unsplash.com/photo-1626015366386-7b3acf034571?w=800', photos: ['https://images.unsplash.com/photo-1626015366386-7b3acf034571?w=400'], popularActivities: ['Pilgrimage', 'Trekking', 'River rafting'], bestSeason: 'May – June, September – October', trending: true, wishlistCount: 3100 },

  // BEACHES
  { name: 'Radhanagar Beach', state: 'Andaman & Nicobar Islands', category: 'beach', description: 'Ranked among the best beaches in Asia by Time magazine, Radhanagar Beach on Havelock Island boasts turquoise waters, pristine white sand and lush jungle backdrop.', shortDescription: 'Asia\'s finest white-sand beach with turquoise waters', lat: 11.9897, lng: 92.9533, imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', photos: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400'], popularActivities: ['Snorkelling', 'Scuba diving', 'Sunset viewing', 'Swimming'], bestSeason: 'November – April', trending: true, wishlistCount: 2850 },
  { name: 'Varkala Beach', state: 'Kerala', category: 'beach', description: 'A unique cliff-side beach with mineral springs, where 15m red laterite cliffs dramatically meet the Arabian Sea. The cliff-top promenade is lined with restaurants and yoga centres.', shortDescription: 'Dramatic cliff-top beach with natural springs', lat: 8.7379, lng: 76.7163, imageUrl: 'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?w=800', photos: ['https://images.unsplash.com/photo-1599640842225-85d111c60e6b?w=400'], popularActivities: ['Cliff diving', 'Yoga', 'Ayurvedic spa', 'Surfing'], bestSeason: 'September – March', trending: false, wishlistCount: 1560 },
  { name: 'Goa Beaches', state: 'Goa', category: 'beach', description: 'India\'s beach capital offers 101km of coastline with beaches ranging from lively party spots like Baga to tranquil retreats like Palolem. Portuguese colonial heritage adds unique cultural flavour.', shortDescription: 'India\'s beach capital with vibrant nightlife', lat: 15.2993, lng: 74.1240, imageUrl: 'https://images.unsplash.com/photo-1587135991058-8816b028691f?w=800', photos: ['https://images.unsplash.com/photo-1587135991058-8816b028691f?w=400', 'https://images.unsplash.com/photo-1602002418082-dd4a3f5b4a98?w=400'], popularActivities: ['Water sports', 'Nightlife', 'Heritage walks', 'Seafood dining'], bestSeason: 'November – March', trending: true, wishlistCount: 4200 },

  // HILL STATIONS
  { name: 'Coorg', state: 'Karnataka', category: 'hillstation', description: 'Known as the Scotland of India, Coorg is a misty hill station blanketed in coffee and spice plantations. The fragrant air, rolling hills and rich Kodava culture make it an enchanting getaway.', shortDescription: 'Coffee country with misty hills and rich culture', lat: 12.3375, lng: 75.8069, imageUrl: 'https://images.unsplash.com/photo-1610126789517-a4cd11c42ec7?w=800', photos: ['https://images.unsplash.com/photo-1610126789517-a4cd11c42ec7?w=400'], popularActivities: ['Coffee plantation tours', 'River rafting', 'Elephant rides', 'Trekking'], bestSeason: 'October – March', trending: true, wishlistCount: 2100 },
  { name: 'Munnar', state: 'Kerala', category: 'hillstation', description: 'A paradise of rolling hills carpeted with lush tea plantations at 1,600m altitude. Munnar\'s cool climate, misty mountains, cascading waterfalls and sprawling tea estates draw visitors year-round.', shortDescription: 'Rolling tea plantations and misty mountain air', lat: 10.0889, lng: 77.0595, imageUrl: 'https://images.unsplash.com/photo-1602343168117-bb8a12d7c180?w=800', photos: ['https://images.unsplash.com/photo-1602343168117-bb8a12d7c180?w=400'], popularActivities: ['Tea factory tours', 'Trekking', 'Wildlife spotting', 'Boating'], bestSeason: 'September – March', trending: true, wishlistCount: 2800 },
  { name: 'Darjeeling', state: 'West Bengal', category: 'hillstation', description: 'The Queen of Hills perched at 2,042m in the Himalayas, famous for its distinctive tea, the Darjeeling Himalayan Railway and awe-inspiring views of Kangchenjunga, the world\'s third-highest peak.', shortDescription: 'Queen of Hills famed for tea and Himalayan views', lat: 27.0410, lng: 88.2663, imageUrl: 'https://images.unsplash.com/photo-1561043433-aaf687c4cf04?w=800', photos: ['https://images.unsplash.com/photo-1561043433-aaf687c4cf04?w=400'], popularActivities: ['Toy train ride', 'Tiger Hill sunrise', 'Tea garden visit', 'Trekking'], bestSeason: 'March – May, October – November', trending: true, wishlistCount: 3200 },
  { name: 'Ooty', state: 'Tamil Nadu', category: 'hillstation', description: 'The Nilgiris\' crown jewel at 2,240m, Ooty enchants with its colonial bungalows, botanical gardens, shimmering Ooty Lake and the iconic Nilgiri Mountain Railway UNESCO World Heritage toy train.', shortDescription: 'Nilgiris queen with colonial charm and botanical beauty', lat: 11.4102, lng: 76.6950, imageUrl: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800', photos: ['https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=400'], popularActivities: ['Toy train ride', 'Boating', 'Tea tasting', 'Horse riding'], bestSeason: 'April – June, September – November', trending: false, wishlistCount: 1900 },
  { name: 'Manali', state: 'Himachal Pradesh', category: 'hillstation', description: 'A high-altitude Himalayan resort town at the northern end of the Kullu Valley, gateway to Rohtang Pass and Lahaul and Spiti. A paradise for adventure seekers and honeymooners alike.', shortDescription: 'Gateway to the Himalayas, adventure capital of India', lat: 32.2396, lng: 77.1887, imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800', photos: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=400'], popularActivities: ['Skiing', 'River rafting', 'Paragliding', 'Camping'], bestSeason: 'October – June', trending: true, wishlistCount: 4500 },

  // MONUMENTS
  { name: 'Taj Mahal', state: 'Uttar Pradesh', category: 'monument', description: 'The world\'s most iconic monument of love, built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal. This white marble mausoleum, a UNESCO World Heritage Site, draws millions with its ethereal beauty.', shortDescription: 'Iconic white marble monument of eternal love', lat: 27.1751, lng: 78.0421, imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800', photos: ['https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400', 'https://images.unsplash.com/photo-1587135991058-8816b028691f?w=400'], popularActivities: ['Sunrise visit', 'Photography', 'Agra Fort visit', 'Guided heritage tour'], bestSeason: 'October – March', trending: true, wishlistCount: 6500 },
  { name: 'Hampi', state: 'Karnataka', category: 'monument', description: 'A UNESCO World Heritage Site and erstwhile capital of the Vijayanagara Empire spanning 4,187 sq km of boulder-strewn landscape. Over 1,600 surviving remains of the last great Hindu kingdom dot this surreal terrain.', shortDescription: 'Ancient Vijayanagara Empire ruins in surreal boulder landscape', lat: 15.3350, lng: 76.4600, imageUrl: 'https://images.unsplash.com/photo-1600697229585-95c2dc6c1c55?w=800', photos: ['https://images.unsplash.com/photo-1600697229585-95c2dc6c1c55?w=400'], popularActivities: ['Temple hopping', 'Coracle ride', 'Photography', 'Rock climbing'], bestSeason: 'November – February', trending: true, wishlistCount: 2200 },
  { name: 'Khajuraho', state: 'Madhya Pradesh', category: 'monument', description: 'A UNESCO World Heritage Site renowned for its group of medieval Hindu and Jain temples, famous for their Nagara-style architectural symbolism and erotic sculptures representing the Hindu view of life.', shortDescription: 'Medieval temples with exquisite erotic sculptures', lat: 24.8318, lng: 79.9199, imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800', photos: ['https://images.unsplash.com/photo-1548013146-72479768bada?w=400'], popularActivities: ['Light and sound show', 'Archaeological museum', 'Temple circuits'], bestSeason: 'October – March', trending: false, wishlistCount: 1400 },
  { name: 'Jaisalmer Fort', state: 'Rajasthan', category: 'monument', description: 'One of the world\'s few living forts, rising 99m from the Rajasthan desert. The golden sandstone walls glow at sunset, earning it the epithet "Sonar Quila" (Golden Fort). Within its walls, thousands still call it home.', shortDescription: 'Living golden fort rising from the Thar Desert', lat: 26.9124, lng: 70.9083, imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed31069?w=800', photos: ['https://images.unsplash.com/photo-1477587458883-47145ed31069?w=400'], popularActivities: ['Desert safari', 'Camel ride', 'Jain temple visit', 'Folk music evening'], bestSeason: 'October – March', trending: true, wishlistCount: 2900 },

  // ISLANDS
  { name: 'Lakshadweep', state: 'Lakshadweep', category: 'island', description: 'India\'s smallest Union Territory comprising 36 coral islands in the Arabian Sea. Crystal-clear lagoons, pristine coral reefs and untouched white-sand beaches make it one of the least-visited and most pristine ecosystems.', shortDescription: 'Pristine coral islands with crystal lagoons', lat: 10.5667, lng: 72.6417, imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800', photos: ['https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400'], popularActivities: ['Snorkelling', 'Glass-bottom boat', 'Kayaking', 'Scuba diving'], bestSeason: 'October – May', trending: true, wishlistCount: 2100 },
  { name: 'Neil Island', state: 'Andaman & Nicobar Islands', category: 'island', description: 'A quiet paradise known for its natural rock formation "Howrah Bridge", stunning beaches and laid-back vibe. Neil Island offers a tranquil escape with pristine snorkelling sites and bioluminescent bays.', shortDescription: 'Tranquil island with natural rock bridge and bioluminescent bay', lat: 11.8297, lng: 93.0519, imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800', photos: ['https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=400'], popularActivities: ['Snorkelling', 'Cycling around island', 'Night bioluminescence tour'], bestSeason: 'November – April', trending: false, wishlistCount: 980 },

  // WILDLIFE
  { name: 'Jim Corbett National Park', state: 'Uttarakhand', category: 'wildlife', description: 'India\'s oldest national park and the birthplace of Project Tiger. The 520 sq km park hosts the highest density of Bengal tigers in the world, along with elephants, leopards and over 650 bird species.', shortDescription: 'India\'s oldest national park, Bengal tiger heartland', lat: 29.5300, lng: 78.7747, imageUrl: 'https://images.unsplash.com/photo-1615811648503-479d65e46fd3?w=800', photos: ['https://images.unsplash.com/photo-1615811648503-479d65e46fd3?w=400'], popularActivities: ['Jeep safari', 'Elephant safari', 'Bird watching', 'River fishing'], bestSeason: 'November – June', trending: true, wishlistCount: 2700 },
  { name: 'Ranthambore National Park', state: 'Rajasthan', category: 'wildlife', description: 'One of India\'s finest wildlife parks, where the majestic Bengal tiger is frequently spotted against a dramatic backdrop of 10th-century Ranthambore Fort ruins — a uniquely photogenic wildlife experience.', shortDescription: 'Tigers amid ancient fort ruins — India\'s most photogenic safari', lat: 26.0173, lng: 76.5026, imageUrl: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800', photos: ['https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=400'], popularActivities: ['Tiger safari', 'Fort visit', 'Bird watching', 'Photography'], bestSeason: 'October – June', trending: true, wishlistCount: 3100 },
  { name: 'Kaziranga National Park', state: 'Assam', category: 'wildlife', description: 'A UNESCO World Heritage Site hosting two-thirds of the world\'s great one-horned rhinoceroses. The park also has the highest density of tigers among protected areas, plus wild water buffalos and swamp deer.', shortDescription: 'Home to two-thirds of the world\'s one-horned rhinos', lat: 26.6638, lng: 93.3755, imageUrl: 'https://images.unsplash.com/photo-1605649461784-edc3e0d6c0b1?w=800', photos: ['https://images.unsplash.com/photo-1605649461784-edc3e0d6c0b1?w=400'], popularActivities: ['Elephant safari', 'Jeep safari', 'Bird watching', 'River cruise'], bestSeason: 'November – April', trending: false, wishlistCount: 1650 },

  // CITIES
  { name: 'Varanasi', state: 'Uttar Pradesh', category: 'city', description: 'One of the world\'s oldest continuously inhabited cities and Hinduism\'s holiest city, straddling the banks of the sacred Ganges. The spectacular Ganga Aarti, ancient ghats and timeless rituals make it a transcendental experience.', shortDescription: 'World\'s oldest city, spiritual heart of India', lat: 25.3176, lng: 82.9739, imageUrl: 'https://images.unsplash.com/photo-1561515959-b18d43cb21f0?w=800', photos: ['https://images.unsplash.com/photo-1561515959-b18d43cb21f0?w=400', 'https://images.unsplash.com/photo-1545569258-a59f04e9d03e?w=400'], popularActivities: ['Ganga Aarti', 'Boat ride on Ganga', 'Temple circuit', 'Silk shopping'], bestSeason: 'October – March', trending: true, wishlistCount: 3800 },
  { name: 'Jaipur', state: 'Rajasthan', category: 'city', description: 'The Pink City, capital of Rajasthan, is a magnificent showcase of Rajput architecture with palaces like Hawa Mahal and City Palace surrounded by fortified walls. A living museum of India\'s royal heritage.', shortDescription: 'The Pink City — royal palaces and Rajput grandeur', lat: 26.9124, lng: 75.7873, imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed31069?w=800', photos: ['https://images.unsplash.com/photo-1477587458883-47145ed31069?w=400'], popularActivities: ['Amber Fort', 'Hawa Mahal', 'Elephant ride', 'Block printing'], bestSeason: 'October – March', trending: true, wishlistCount: 4100 },
  { name: 'Pondicherry', state: 'Puducherry', category: 'city', description: 'A charming French colonial enclave on the Coromandel Coast where Gallic charm meets Tamil culture. Colourful Creole houses, leafy boulevards, pristine beaches, ashrams and world-class French cuisine define this coastal gem.', shortDescription: 'French colonial charm meets Tamil culture on the coast', lat: 11.9416, lng: 79.8083, imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800', photos: ['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=400'], popularActivities: ['Heritage walking tour', 'Auroville visit', 'Beach cycling', 'Yoga retreat'], bestSeason: 'October – February', trending: true, wishlistCount: 2500 },
  { name: 'Udaipur', state: 'Rajasthan', category: 'city', description: 'The City of Lakes and Venice of the East, Udaipur is centred on the shimmering Lake Pichola with its island palaces. The magnificent City Palace complex, romantic boat rides and vibrant bazaars create an unforgettable experience.', shortDescription: 'City of Lakes — the Venice of the East', lat: 24.5854, lng: 73.7125, imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800', photos: ['https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=400'], popularActivities: ['Lake Pichola boat ride', 'City Palace', 'Arsi Vilas night view', 'Puppet show'], bestSeason: 'September – March', trending: true, wishlistCount: 3600 },
  { name: 'Mysuru', state: 'Karnataka', category: 'city', description: 'The City of Palaces, Mysuru retains an old-world charm with its magnificent Mysore Palace illuminated by 97,000 light bulbs, fragrant sandalwood and incense markets, and the grand Dasara celebrations.', shortDescription: 'City of Palaces with royal grandeur and Dasara festivities', lat: 12.2958, lng: 76.6394, imageUrl: 'https://images.unsplash.com/photo-1600697229585-95c2dc6c1c55?w=800', photos: ['https://images.unsplash.com/photo-1600697229585-95c2dc6c1c55?w=400'], popularActivities: ['Mysore Palace', 'Chamundi Hill', 'Brindavan Gardens', 'Silk shopping'], bestSeason: 'October – March', trending: false, wishlistCount: 2000 },

  // FOOD destinations
  { name: 'Amritsar', state: 'Punjab', category: 'food', description: 'The spiritual and cultural centre of the Sikh faith, home to the breathtaking Golden Temple. But Amritsar is equally famous for its legendary cuisine — butter naan, dal makhani, and the iconic Amritsari kulcha served straight from the tandoor.', shortDescription: 'Golden Temple city with legendary Punjabi cuisine', lat: 31.6340, lng: 74.8723, imageUrl: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800', photos: ['https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=400'], popularActivities: ['Golden Temple', 'Wagah Border ceremony', 'Food walk', 'Jallianwala Bagh'], bestSeason: 'October – March', trending: true, wishlistCount: 3900 },
  { name: 'Hyderabad', state: 'Telangana', category: 'food', description: 'The City of Nizams, globally celebrated for its world-famous Hyderabadi Biryani slow-cooked to perfection. The city blends Islamic grandeur (Charminar, Golconda Fort) with a thriving tech hub and dazzling cuisine culture.', shortDescription: 'City of Nizams, home of the legendary Hyderabadi Biryani', lat: 17.3850, lng: 78.4867, imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800', photos: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400'], popularActivities: ['Biryani trail', 'Charminar', 'Golconda Fort', 'Pearl shopping'], bestSeason: 'October – February', trending: false, wishlistCount: 2800 },
  { name: 'Kolkata', state: 'West Bengal', category: 'food', description: 'The City of Joy, Kolkata\'s food scene is a passionate culinary journey through street food legends — kathi rolls, puchkas, misti doi, sandesh and mishti — woven into a city pulsating with art, literature and colonial grandeur.', shortDescription: 'City of Joy with iconic street food and colonial soul', lat: 22.5726, lng: 88.3639, imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400'], popularActivities: ['Street food tour', 'Victoria Memorial', 'Durga Puja', 'Howrah Bridge walk'], bestSeason: 'October – February', trending: false, wishlistCount: 2300 },

  // AMUSEMENT
  { name: 'Imagica Theme Park', state: 'Maharashtra', category: 'amusement', description: 'India\'s largest theme park near Mumbai, spanning 130 acres with 39 exciting rides and attractions spread across three parks — Adlabs Imagica, Aquamagica and Snow Park — offering world-class entertainment for all ages.', shortDescription: 'India\'s largest theme park near Mumbai', lat: 18.6878, lng: 73.2004, imageUrl: 'https://images.unsplash.com/photo-1559553012-7e6fb51ee9c3?w=800', photos: ['https://images.unsplash.com/photo-1559553012-7e6fb51ee9c3?w=400'], popularActivities: ['Roller coasters', 'Water rides', 'Snow park', 'Shows'], bestSeason: 'Year round', trending: false, wishlistCount: 1200 },
  { name: 'Wonderla Bangalore', state: 'Karnataka', category: 'amusement', description: 'South India\'s most popular amusement park on the Mysore Highway offers 60+ thrilling rides including wet, dry and high-thrill rides, plus beautiful resort facilities and wave pools.', shortDescription: 'South India\'s most popular amusement and water park', lat: 12.8404, lng: 77.3781, imageUrl: 'https://images.unsplash.com/photo-1575408264798-b50b252663e6?w=800', photos: ['https://images.unsplash.com/photo-1575408264798-b50b252663e6?w=400'], popularActivities: ['Wave pool', 'Rain disco', 'High-thrill coasters', 'Water rides'], bestSeason: 'October – March', trending: false, wishlistCount: 1100 },

  // More diversity
  { name: 'Valley of Flowers', state: 'Uttarakhand', category: 'mountain', description: 'A UNESCO World Heritage Site and national park high in the Himalayas, celebrated for its expansive meadows of endemic alpine flowers. During peak bloom (July–August) over 500 species of flowers carpet the valley floor.', shortDescription: 'UNESCO alpine valley blanketed with 500+ flower species', lat: 30.7283, lng: 79.6055, imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800', photos: ['https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400'], popularActivities: ['Trekking', 'Photography', 'Hemkund Sahib visit', 'Birdwatching'], bestSeason: 'July – August', trending: true, wishlistCount: 1800 },
  { name: 'Sundarbans', state: 'West Bengal', category: 'wildlife', description: 'The world\'s largest mangrove forest and a UNESCO World Heritage Site, the Sundarbans is home to the Royal Bengal Tiger who swims between islands. The labyrinthine network of waterways creates an entirely unique ecosystem.', shortDescription: 'World\'s largest mangrove forest, home of swimming tigers', lat: 21.9497, lng: 88.9861, imageUrl: 'https://images.unsplash.com/photo-1549693578-a0f97bb47e1a?w=800', photos: ['https://images.unsplash.com/photo-1549693578-a0f97bb47e1a?w=400'], popularActivities: ['Boat safari', 'Tiger sighting', 'Bird watching', 'Village visits'], bestSeason: 'October – March', trending: false, wishlistCount: 1400 },
  { name: 'Alleppey Backwaters', state: 'Kerala', category: 'city', description: 'The Venice of the East, Alleppey\'s 1,500km of interlocking canals, rivers, lakes and inlets are best explored on a traditional Kerala houseboat (kettuvallam). Gliding past rice paddies and coconut groves is utterly serene.', shortDescription: 'Kerala\'s backwater paradise best experienced on a houseboat', lat: 9.4981, lng: 76.3388, imageUrl: 'https://images.unsplash.com/photo-1602002418082-dd4a3f5b4a98?w=800', photos: ['https://images.unsplash.com/photo-1602002418082-dd4a3f5b4a98?w=400'], popularActivities: ['Houseboat cruise', 'Canoeing', 'Village walk', 'Snake boat races'], bestSeason: 'November – February', trending: true, wishlistCount: 3400 },
  { name: 'Rann of Kutch', state: 'Gujarat', category: 'monument', description: 'The world\'s largest salt desert transforms into a breathtaking white moonscape under the full moon of winter. The Rann Utsav (festival) celebrates Kutchi culture with folk dancing, handicrafts, and local cuisine.', shortDescription: 'World\'s largest salt desert — ethereal under the full moon', lat: 23.7337, lng: 69.8597, imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800', photos: ['https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=400'], popularActivities: ['Camel safari', 'Folk performance', 'Flamingo watching', 'Photography at sunset'], bestSeason: 'November – February', trending: true, wishlistCount: 2600 },
  { name: 'Tawang', state: 'Arunachal Pradesh', category: 'mountain', description: 'A remote Himalayan town at 3,048m, Tawang is home to the largest Buddhist monastery in India and second-largest in the world. Snow-capped mountains, pristine lakes like Madhuri Lake and Buddhist culture create a magical atmosphere.', shortDescription: 'Remote Himalayan town with India\'s largest monastery', lat: 27.5860, lng: 91.8594, imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800', photos: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=400'], popularActivities: ['Tawang Monastery', 'Madhuri Lake', 'Sela Pass', 'Bumla Pass'], bestSeason: 'April – October', trending: false, wishlistCount: 1100 },
  { name: 'Rishikesh', state: 'Uttarakhand', category: 'city', description: 'The Yoga Capital of the World and gateway to the Char Dham pilgrimage, Rishikesh sits where the Ganges exits the Himalayas. The iconic Laxman Jhula bridge, riverside ashrams and exhilarating white-water rafting make it extraordinary.', shortDescription: 'Yoga capital, adventure hub and spiritual gateway', lat: 30.0869, lng: 78.2676, imageUrl: 'https://images.unsplash.com/photo-1585406941573-fca0edf6c1d0?w=800', photos: ['https://images.unsplash.com/photo-1585406941573-fca0edf6c1d0?w=400'], popularActivities: ['White water rafting', 'Yoga & meditation', 'Bungee jumping', 'Ganga Aarti'], bestSeason: 'September – November, March – May', trending: true, wishlistCount: 3700 },
  { name: 'Meghalaya Caves', state: 'Meghalaya', category: 'mountain', description: 'Meghalaya, meaning "abode of clouds", has the world\'s longest cave systems, including Krem Liat Prah. The state also has living root bridges, double-decker natural marvels woven from rubber tree roots by the Khasi people over centuries.', shortDescription: 'Abode of clouds with living root bridges and world\'s longest caves', lat: 25.4670, lng: 91.3662, imageUrl: 'https://images.unsplash.com/photo-1601918774950-8d9d38ad1c96?w=800', photos: ['https://images.unsplash.com/photo-1601918774950-8d9d38ad1c96?w=400'], popularActivities: ['Cave exploration', 'Living root bridge trek', 'Waterfall visits', 'Caving'], bestSeason: 'October – May', trending: false, wishlistCount: 1600 },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');
    await Place.deleteMany({});
    console.log('Cleared existing places');
    await Place.insertMany(places);
    console.log(`Seeded ${places.length} Indian places successfully!`);
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
